// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
)

type Album struct {
	ID   int64
	Name string
	Bio  sql.NullString
}

type Test struct {
	ID        interface{}
	CreatedAt sql.NullTime
}
