---
version: "3"

tasks:
  run:
    deps:
      - build
    summary: Runs the backend server
    cmds:
      - ./server
  watch:
    summary: Watch for changes to the backend server and rebuild. (Make sure watchexec is installed)
    cmds:
      - watchexec -r -e go -- task run
  build:
    summary: Build backend executables
    sources:
      - ./**/*.go
    generates:
      - server
    cmds:
      - go mod download
      - go build -o server ./cmd/server
  clean:
    summary: Delete build files
    cmds:
      - rm -f server
  test:
    summary: Run backend tests
    cmds:
      - go test ./...
  lint:
    summary: Run lint checks
    cmds:
      - golangci-lint run ./...
  check:
    summary: Run static analysis checks
    cmds:
      - golangci-lint run ./...
      - go mod tidy
      - go fmt ./...
      - go vet ./...
